# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_usernames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserNames',
        ),
    ]
