# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_delete_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
