# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
