# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0006_createlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlogin',
            name='timestamp_add',
        ),
        migrations.RemoveField(
            model_name='createlogin',
            name='timestamp_update',
        ),
    ]
